version: 2.1

jobs:
  run-ci:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: 
        - name: "Install dependencies"
        - command: sudo apt-get update && sudo apt-get install -y cmake ninja-build googletest googletest-tools libgtest-dev qtbase5-dev qt5-qmake
      - run: cmake -B build/ -G Ninja
      - run: ninja -C build/
      - run: ninja -C build/ run_tests

workflows:
  run-ci-workflow:
    jobs:
      - run-ci
